server:
  port: 8088

spring:
  redis:
    sentinel:
      master: mymaster
      nodes: redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
    cluster:
#      nodes: redis-master:6379
      nodes: redis-master:6379,redis-slave:6379
      max-redirects: 3
#    host: localhost
#    port: 6379
