version: '3.6'

services:
  redis-master:
    image: redis:5.0.5-alpine3.10
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
    deploy:
      replicas: 1
    networks:
      - redis-net
  redis-slave:
    image: redis:5.0.5-alpine3.10
    command: redis-server --slaveof redis-master 6379
    deploy:
      replicas: 1
    networks:
      - redis-net

  redis-sentinel-1:
    image: docker.sense.io/redis-sentinel:5.0.5-apline3.10
    deploy:
      replicas: 1
    networks:
      - redis-net
  redis-sentinel-2:
    image: docker.sense.io/redis-sentinel:5.0.5-apline3.10
    deploy:
      replicas: 1
    networks:
      - redis-net
  redis-sentinel-3:
    image: docker.sense.io/redis-sentinel:5.0.5-apline3.10
    deploy:
      replicas: 1
    networks:
      - redis-net

  redis-demo:
    image: docker.sense.io/redis-demo:latest
    depends_on:
      - redis-master
      - redis-slave
    deploy:
      replicas: 1
    networks:
      - redis-net
networks:
  redis-net:
    external: true

